services:
  postgres:
    image: postgres:16-alpine
    container_name: wallet_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wallet_db
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data